/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rictus_exp_JavaExperiment */

#ifndef _Included_org_rictus_exp_JavaExperiment
#define _Included_org_rictus_exp_JavaExperiment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rictus_exp_JavaExperiment
 * Method:    goThere
 * Signature: (Lorg/rictus/exp/Callback;)V
 */
JNIEXPORT void JNICALL Java_org_rictus_exp_JavaExperiment_goThere
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
